name: build

on:
  workflow_call:
  push:
    branches: [ "main" ]  
    paths-ignore:
      - README.md

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
    - name: Distribution Zip
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: :green:distZip
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: green
        path: eflect/green/build/distributions/green-*.*.*.zip
